# .github/workflows/deploy.yml
name: CI/CD
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password \
            | docker login \
                --username AWS \
                --password-stdin <your_account_id>.dkr.ecr.us-east-1.amazonaws.com

      - name: Build and Push Docker Image
        run: |
          docker build -t flask-app ./flask-app
          docker tag flask-app:latest <your_account_id>.dkr.ecr.us-east-1.amazonaws.com/flask-app:latest
          docker push <your_account_id>.dkr.ecr.us-east-1.amazonaws.com/flask-app:latest

      - name: Deploy to EKS
        run: |
          aws eks update-kubeconfig --name eks-dev
          kubectl apply -f k8s/
